# Python excercise: Action & Cognition Computational Cognition

Here are some exercises to test your basic knowledge in Python programming
Author

## 1. String operations

Q1.1: The first and the last name are given as separate string objects. Concatenate these two strings to get "Ada Lovelace" and assign it to the variable $fullname$.

In [1]:
first_name = 'Ada'
last_name = 'Lovelace'

In [2]:
full_name = first_name + ' ' + last_name

Q1.2: Print a simple message "Hello Ada Lovelace, how are you?" using string formatting (Don't print Ada Lovelace explicitly, use $fullname$).

In [3]:
print('Hello {}, how are you?' .format(full_name))

Hello Ada Lovelace, how are you?


## 2. Lists

Q2.1: Initialise a list which contains integer 1, 2, 3, 4. Name the object as $list1$.

In [34]:
list1 = [1, 2, 3, 4]

Q2.2: Insert integer 7 at the end of the $list1$ and integer 5 between integer 3 and 4. 

In [35]:
list1.append(7)
list1.insert(3,5)

Q2.3: Print every element of $list1$ between the first element and the second last element (both inclusive) by using the slice <br>
$\hspace{0.85cm}$ notation. <br>
$\hspace{0.85cm}$ Print every second element of $list1$ by using the slice notation.

In [36]:
print(list1[:-1])
print(list1[::2])

[1, 2, 3, 5, 4]
[1, 3, 4]


Q2.4: Make a deep copy of $list1$ and store it in $list2$.

In [37]:
list2 = list1[:]
#list2 = list1.copy()

list1[0] = 100
print(list2) #check if the copy was deep
list1[0] = 1

[1, 2, 3, 5, 4, 7]


Q2.5: Find out the index of integer 4 and delete it from $list2$ using this information. Remove integer 2 from $list2$ without using the index information.

In [38]:
del list2[list2.index(4)]
list2.remove(2)

Q2.6: Print the difference between $list1$ and $list2$.

In [39]:
print(list(set(list1) - set(list2)))

[2, 4]


## 3. Loops and Conditions

Q3.1: Loop through $list1$ and store all even values into the list $even$ and all odd values into the list $odd$. Print all even values.

In [41]:
even = []
odd = []

for elem in list1:
    if elem%2==0:
        even.append(elem)
    else:
        odd.append(elem)

print(even)

[2, 4]


Q3.2: Loop through the list of new users and check if the user name is already used by comparing each entry with the list of <br>
$\hspace{0.85cm}$ current users. <br>
$\hspace{0.85cm}$ Print a message whether the user name is already taken or it's available. If the user name is already taken, print out <br>
$\hspace{0.85cm}$ the existing user name also.

In [42]:
current_users = ['peter', 'paul', 'marie', 'max']
new_users = ['anna', 'sascha', 'max']

In [43]:
for new_user in new_users:
    if new_user in current_users:
        print('Sorry, the user name {} is already in use.' .format(new_user.title()))
    else:
        print('The user name {} is available.' .format(new_user.title()))

The user name Anna is available.
The user name Sascha is available.
Sorry, the user name Max is already in use.


## 4. Dictionaries

Q4.1: Start with an empty dictionary $cities$ and add at least 4 cities (of your choice) as keys and a subjective rating from 0  <br>
$\hspace{0.85cm}$ (dont want to visit) to 10 (want to visit) as values.

In [45]:
cities = {}

cities['paris'] = 3
cities['kyoto'] = 8
cities['rome'] = 6
cities['limerick'] = 1

Q4.2: Delete one of the key-value-pairs from the dictionary $cities$.

In [51]:
del cities['limerick']
#cities.pop('limerick')

Q4.3: Loop through the dictionary $cities$ and print all key-value-pairs. <br>
$\hspace{0.85cm}$ Example: <br>
$\hspace{0.85cm}$ Key: X <br>
$\hspace{0.85cm}$ Value: Y <br>

In [52]:
for key, value in cities.items():
    print('\nKey: ' + key)
    print('Value: ' + str(value))


Key: paris
Value: 3

Key: kyoto
Value: 8

Key: rome
Value: 6


Q4.4: Loop through the dictionary $cities$ and save all keys into the list $city$. Print all elements of the list $city$ in one line.

In [53]:
city = []

In [54]:
for key in cities.keys():
    city.append(key)
    
print(', '.join(city))

paris, kyoto, rome


Q4.5  Add 'Osnabrueck' with your ranking to the dictionary $cities$

In [ ]:
cities.update({'Osnabrück':9})

Q4.5: Convert the given lists (of same length) into a dictionary. print the dictionary.

In [55]:
name = ['peter', 'paul', 'marie', 'max']
age = [20, 30, 40, 18]

In [56]:
mydict = dict(zip(name,age))
print(mydict)

#mydict = [{'name': f, 'age': c} for f, c in zip(name, age)]

{'peter': 20, 'paul': 30, 'marie': 40, 'max': 18}


## 5. Functions

Q5.1: Write a function that sums up all items of a list. Print the result for $list1$.

In [57]:
def sum_list(numbers):
    #TODO
    return sum_numbers

SyntaxError: unexpected EOF while parsing (<ipython-input-57-334974865360>, line 2)

In [58]:
def sum_list(numbers):
    sum_numbers = 0
    for x in numbers:
        sum_numbers += x
    return sum_numbers

print(sum_list(list1))

22


Q5.2: Write a function that multiplies all items of a list. Print the result for $list1$.

In [ ]:
def multiply_list(numbers):
    #TODO
    return total

In [59]:
def multiply_list(numbers):
    total = 1
    for x in numbers:
        total *= x
    return total

print(multiply_list(list1))

840


Q5.3: Write a function that finds the largest number of a list. Print the result for $list1$.

In [ ]:
def max_num_in_list(numbers):
    #TODO
    return maximum

In [60]:
def max_num_in_list(numbers):
    maximum = numbers[0]
    for a in numbers:
        if a > maximum:
            maximum = a
    return maximum

print(max_num_in_list(list1))

7


Function inside a function, decorator???

Q5.4: Write a function to check if a given name already exists in the dictionary $mydict$ of Q4.6 

In [ ]:
def is_name_present(x):
  if x in mydict:
      print('Name is present in the dictionary')
  else:
      print('Name is missing in the dictionary')
is_name_present('paul')
is_name_present('anna')

Q5.5: Write a function that multiplies a vector by a scalar using list comprehensions

In [ ]:
def scale(A, x): return [ai*x for ai in A]
print(scale([1,2,3,4], 2))

## 6. Numpy

In [63]:
import numpy as np

Q6.1: Compute a matrix multiplication of two given numpy arrays $x$ and $y$.

In [79]:
x = np.reshape(np.arange(9),(3,3))
print("First array:")
print(x)
y = np.reshape(np.arange(9,18),(3,3))
print("Second array:")
print(y)

First array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Second array:
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [84]:
matmul = x @ y
# matmul = np.matmul(x,y)
print("Matrix multiplication of two arrays:")
print(matmul)

Matrix multiplication of two arrays:
[[ 42  45  48]
 [150 162 174]
 [258 279 300]]


Q6.2: Compute a element-wise multiplication of $x$ and $y$.

In [86]:
elemmul = x * y
# elemmul = np.multiply(x,y)
print("Element-wise multiplication of two arrays: ")
print(elemmul)

Element-wise multiplication of two arrays: 
[[  0  10  22]
 [ 36  52  70]
 [ 90 112 136]]


Q6.3: Select an element that can integer-divided with 3 from a given array $arr$ using a mask.

In [88]:
arr = np.reshape(np.arange(8),(2,4))
mask = # TODO
print(arr)
print(arr[mask])

SyntaxError: invalid syntax (<ipython-input-88-80f665d5cf00>, line 2)

In [89]:
arr = np.reshape(np.arange(8),(2,4))
mask = arr % 3 == 0
print(arr)
print(arr[mask])

[[0 1 2 3]
 [4 5 6 7]]
[0 3 6]
